### ISSUE TITLE
List MST for avatar

### ISSUE THREAD

**Issue by canguruhh** [mvs-org/avatar-portal#1]
List all MST an an avatar from the explorer

**Comment by canguruhh** [comment]
@LaurentSalou will add the explorer function. portal api will basically just forward the request to the explorer

**Comment by LaurentSalou** [comment]
Added in the explorer api v2:
https://github.com/mvs-org/mvs-explorer-api-v2/commit/32acabe71e698e3f8f705d58e8eeca882a278b12

Example:
https://explorer-testnet.mvs.org/api/v2/avatar/laurent/assets
